apiVersion: v2
type: application

name: squidex7
icon: https://raw.githubusercontent.com/Squidex/squidex/master/media/logo-squared.png
description: Squidex CMS v7.0 and newer

version: 1.0.3
appVersion: "7.15.0"

home: https://squidex.io/

keywords:
  - cms
  - headless-cms
  - mongodb
  - csharp
  - asp-net-core
  - asp-net

sources:
  - https://github.com/Squidex/squidex

dependencies:
  - name: mongodb-replicaset
    version: 3.9.6
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mongodb-replicaset.enabled
