apiVersion: v1
entries:
  squidex:
  - apiVersion: v2
    appVersion: 5.9.0
    created: "2022-08-10T10:38:40.2985659+02:00"
    dependencies:
    - condition: mongodb-replicaset.enabled
      name: mongodb-replicaset
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 3.9.6
    description: Squidex CMS
    digest: 566b4d063d2717e00fc04b35bf594869dc9e5398bb08da13b542a5497dd4dc19
    home: https://squidex.io/
    keywords:
    - cms
    - headless-cms
    - mongodb
    - csharp
    - asp-net-core
    - asp-net
    name: squidex
    sources:
    - https://github.com/Squidex/squidex
    type: application
    urls:
    - squidex-1.3.0.tgz
    version: 1.3.0
  squidex7:
  - apiVersion: v2
    appVersion: 7.0.2
    created: "2022-08-10T10:38:40.2995659+02:00"
    dependencies:
    - condition: mongodb-replicaset.enabled
      name: mongodb-replicaset
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 3.9.6
    description: Squidex CMS v7.0 and newer
    digest: 9cc4c40f4a5825a33835fa8f0fc4c40389f2da96b247a9425dd999b90ee1457f
    home: https://squidex.io/
    icon: https://raw.githubusercontent.com/Squidex/squidex/master/media/logo-squared.png
    keywords:
    - cms
    - headless-cms
    - mongodb
    - csharp
    - asp-net-core
    - asp-net
    name: squidex7
    sources:
    - https://github.com/Squidex/squidex
    type: application
    urls:
    - squidex7-1.0.0.tgz
    version: 1.0.0
generated: "2022-08-10T10:38:40.2965702+02:00"
