apiVersion: v1
entries:
  squidex:
  - apiVersion: v2
    appVersion: 5.8.0

    created: "2021-09-13T13:02:07.445459+02:00"
    dependencies:
    - condition: mongodb-replicaset.enabled
      name: mongodb-replicaset
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 3.9.6
    description: Squidex CMS
    digest: 4837131004d23a1de21eb6d8d8576e6fadad990a49136af061d2c7e43bbaff9d
    home: https://squidex.io/
    keywords:
    - cms
    - headless-cms
    - mongodb
    - csharp
    - asp-net-core
    - asp-net
    name: squidex
    sources:
    - https://github.com/Squidex/squidex
    type: application
    urls:
    - https://squidex.github.io/squidex/helm/squidex-1.0.0.tgz
    version: 1.0.0
generated: "2021-09-13T13:02:07.441734+02:00"