name: Marketplace - GCP
concurrency: marketplace-gcp

on:
  release:
    types: [released]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        if: false
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: gcp.pkr.hcl
        working-directory: packer/

  publish:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        if: false
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: gcp.pkr.hcl
        env:
          PACKER_LOG: 1
        working-directory: packer/
